### PR TITLE
Fix evaluation y expectation

### PR DESCRIPTION
**Pull request by ikkoham**
### Summary

Fix first part of #895.

I think this needs more tests.
~~I will write later.~~
I have written it.

### CODE REVIEW

**Comment by atilag** [comment]
I'm having a hard time figuring out what did you actually change, there seems to be a lot of formatting changes but not changes in the logic? (apart from tests).

**Comment by ikkoham** [comment]
Thanks for the review.
The change can be seen in [my first commit](https://github.com/Qiskit/qiskit-aer/pull/898/commits/c9b9d09f0e78a5913d6dc9573f257535b3b15cc6).

The second commit is adding the test, and
the rest are format changes.

**Review by yaelbh — APPROVED** [review]
Looks good, thanks a lot for spotting and fixing it

**Comment by ikkoham** [comment]
I've added a release note.

**Pull request merged**
