### PR TITLE
Release 0.7.1

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

Backport of bugfixs and preparation for the 0.7.1 release.

### CODE REVIEW

**Comment by mtreinish** [comment]
This LGTM, were we waiting for something else to backport here?

**Comment by vvilpas** [comment]
If there is still time, we can wait for #859. I've checked that full gpu wheel build works though there was a timeout error on a regular python3.8 tests run. Is currently running regular CI (no more gpu builds). 
If there is no time we can leave it for a `0.7.2`.

**Review by mtreinish — APPROVED** [review]
LGTM, but before merging someone else should check the release note I just added for the changes to the GPU build that we backported.

**Review by vvilpas — APPROVED** [review]
LGTM!

**Pull request merged**
