### PR TITLE
Release 0.13.2

### PR DESCRIPTION
**Pull request by doichanj**
### Summary
This PR is for fix release 0.13.2

### Details and comments

This release includes:
#2023 
#2026 
#1971 
#2016 
#2014
#2008 
#2006 
#2012 
#2013
#2022 
#2024 
#2018

### CODE REVIEW

**Comment by jakelishman** [comment]
Could we try pulling #2022 in?

**Comment by doichanj** [comment]
I think #2002 is already merged in 0.13.1

**Comment by doichanj** [comment]
@hhorii said if we include #2022, we have to release 0.14 not 0.13.2. but I think we can release 0.14 instead of 0.13.2, which is better?

**Comment by jakelishman** [comment]
We can release Python 3.12 support without a new major version, I think (so in Are 0.13.2) - we did it for Python 3.11 support in Aer 0.11.2 last year. There's no feature changes in the code, just the build process.

**Review by hhorii — APPROVED** [review]
LGTM

**Pull request merged**
