### PR TITLE
Fixed a typo in quantum_error.py

### PR DESCRIPTION
**Pull request by kyeteraydeniz**
Fixed a typo in "to_instruction" and in "to_quantumchannel".

### CODE REVIEW

**Comment by chriseclectic** [comment]
Thanks @kyeteraydeniz! Could you combine this with PR #382 rather than doing a separate PR for each typo

**Comment by kyeteraydeniz** [comment]
> Thanks @kyeteraydeniz! Could you combine your multiple typo PRS into a single one

Sure, will do that...

**Comment by atilag** [comment]
@kyeteraydeniz need any help squashing all the PRs into one?

**Comment by kyeteraydeniz** [comment]
> @kyeteraydeniz need any help squashing all the PRs into one?
> You can just create a new one or use one of the existing to squash there and close the others

I cannot see Squash and Merge. How do I do the squashing?

**Comment by chriseclectic** [comment]
@kyeteraydeniz I created PRs on your fork for you to merge them into one: https://github.com/kyeteraydeniz/qiskit-aer/pulls

**Comment by atilag** [comment]
@kyeteraydeniz ping me if I can help you here. Thanks for your effort!

**Comment by chriseclectic** [comment]
Closing since these typos are fixed in #427

**Pull request closed without merging**
