### PR TITLE
Release 0.7.3 backports

### PR DESCRIPTION
**Pull request by chriseclectic**
### Summary

Backports for bugfix release 0.7.3

### CODE REVIEW

**Comment by mtreinish** [comment]
We should probably backport #1071 too

**Comment by yaelbh** [comment]
@chriseclectic @mtreinish Can we merge and include #1088 ?

**Comment by mtreinish** [comment]
> @chriseclectic @mtreinish Can we merge and include #1088 ?

I think that this is probably a bit too risky from a regression PoV for a backport especially so close to the bugfix release. I also personally view it as a new feature, adding support for new gates to MPS, instead of a bugfix. While it brings it up to parity with the other simulation methods it's still a new feature for MPS.

**Comment by yaelbh** [comment]
I agree, I didn't realize it was a bugfix release

**Pull request merged**
