### PR TITLE
Corrected Find NumPy in src/open_pulse

### PR DESCRIPTION
**Pull request by doichanj**
### Summary
I have corrected format of find NumPy in src/open_pulse/CMakeLists.txt to find correct NumPy installed on Anaconda instead of finding in /usr/include.

### Details and comments
find_package(Python REQUIRED COMPONENTS NumPy) can find NumPy installed by Anaconda and the path is set to Python_NumPy_INCLUDE_DIRS

### CODE REVIEW

**Comment by atilag** [comment]
>  have a virtual environment (python3.8 -m venv ~/.virtualenv/test_38) in MacOS and instead of finding the numpy installed there, now it finds the default MacOS version. Any idea how can we preserve the previous behaviour as well?

@doichanj any comment on this?

**Comment by chriseclectic** [comment]
Is there any activity on this? Otherwise I will close.

**Comment by doichanj** [comment]
I still cannot compile without this change on Power environment without having root permission. But I think it is OK to close this.

**Comment by vvilpas** [comment]
I think I might have found a solution. Let's see if CI pass.

**Review by vvilpas — APPROVED** [review]
Looks good

**Pull request merged**
