### PR TITLE
Support for initialization from Statevector

### PR DESCRIPTION
**Pull request by derwind**
### Summary

This PR is derived from #1621 where the request to construct AerStatevector directly from Terra's Statevector was discussed.

### Details and comments

- Add the implementation suggested in [#1621](https://github.com/Qiskit/qiskit-aer/pull/1621) (see https://github.com/Qiskit/qiskit-aer/pull/1621#discussion_r997788572)
- Update documentations
- Add related unittests

### CODE REVIEW

**Review by hhorii — APPROVED** [review]

**Comment by hhorii** [comment]
Could you add a release note (though I have approved this :-) )?

**Comment by derwind** [comment]
Should I place `BRIEF_TITLE-HASH.yaml` directly under `main/releasenotes/notes`? Is the `HASH` part to be decided randomly?

**Comment by jakelishman** [comment]
@derwind: we use `reno` - there are [instructions in the contributing guide](https://github.com/Qiskit/qiskit-aer/blob/main/CONTRIBUTING.md#release-notes) if you're unfamiliar with it.

**Comment by derwind** [comment]
@jakelishman Thank you. I will read the instruction and try!

**Comment by hhorii** [comment]
@jakelishman can we push this to 0.11.2 as stable-backport-potential?
This PR supports a new type of argument for `AerStatevector`. However, as this release note said, original interface should take it and we may be able to say a kind of bugs in the interface.

**Review by jakelishman — COMMENTED** [review]
I think it should be ok to backport - as you say, it kind of is a bug that the initialisation didn't work as expected.

**Review by hhorii — APPROVED** [review]

**Pull request merged**
