### PR TITLE
reduced_basic_noise_model

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
Converts the basic noise model for a full device and maps it to a reduced coupling_map that specifies a subgraph of the device.  This allows for doing noise simulations on sub-graphs of devices without needing to pad the size of a circuit to the full width of the device.

This is meant to be used in conjunction with https://github.com/Qiskit/qiskit-terra/pull/2225

### CODE REVIEW

**Comment by nonhermitian** [comment]
This is failing for reasons that have nothing to do with my PR.

**Comment by chriseclectic** [comment]
I think this would be better as an optional kwarg argument of `basis_device_noise_model` instead of a seperate function.

**Comment by nonhermitian** [comment]
Ideally it would work on any NoiseModel, but they do not include enough info to work on their own.

**Comment by nonhermitian** [comment]
This is superseded by #190

**Pull request closed without merging**
