### PR TITLE
Disable Fusion when running on MPS

### PR DESCRIPTION
**Pull request by merav-aharoni**
### Summary
Fusion optimization does not work correctly on the MPS simulation method. Therefore should be disabled, even when set in the config.

### Details and comments
See failure example in issue #1253.

### CODE REVIEW

**Comment by yaelbh** [comment]
If a user explicitly asked "MPS and enable fusion" then I'm not sure that you can just override the user's request. Maybe invoke an error, or at least print a warning that you override an explicit request.

**Comment by merav-aharoni** [comment]
There are two problems with writing a warning:
1. There is no mechanism for warnings in the C++ code.
2. The default set-up for the config is to set `fusion_enable = True`, so that even when the use does not set this field explicitly, they will get the warning. 
So overall, I prefer not to have a warning.

**Comment by mtreinish** [comment]
> There are two problems with writing a warning:
> 
>     1. There is no mechanism for warnings in the C++ code.

You can generate a python warning with the Python C api. Something like:

```c++
PyErr_WarnEx(PyExc_RuntimeWarning, "This is my warning text", 1);
```

https://docs.python.org/3/c-api/exceptions.html#c.PyErr_WarnEx
https://docs.python.org/3/c-api/exceptions.html#standard-warning-categories

I'm not sure if their is a pybind native way to do that or not, but under the covers pybind is just calling that anyway.

**Comment by merav-aharoni** [comment]
@yaelbh , please let me know if you agree that we are better off without a comment. Except for this point, the PR is ready for merge.

**Comment by yaelbh** [comment]
Yes, it's fine

**Review by chriseclectic — APPROVED** [review]

**Pull request merged**
