### PR TITLE
Qiskit Aer Parallel: support for multi-process and multi-GPU

### PR DESCRIPTION
**Pull request by doichanj**
I added multi-process (MPI and multi-GPU (CUDA) support codes.
I added 2 subclasses in;
src/simulators/qasm/qasm_controller_par.hpp
src/simulators/statevector/qubitvector_par.hpp
and 1 main program in;
contrib/standalone/qasm_controller_par.cpp
for this implementation.

I also added specific codes for the parallelization in 
src/simulators/statevector/qsim_par

I modified CMakeLists.txt to select this implementation when using cmake, and how to build is written in README_parallel.md .

### CODE REVIEW

**Comment by atilag** [comment]
These are 8.5K lines of code to review.
It's going to take A LOT time to review it.
As this is a major change, I'd have loved to have a previous discussion in an issue so we could saw things like general architecture, design, GPU targets, or even the necessity of introducing MPI (as well as the benefits it will bring).
Do you think is feasible to split this PR in at least two? One for the GPU implementation and another one for the MPI one.
Thanks!

**Comment by doichanj** [comment]
MPI version has only about 100 lines of additional codes from non-MPI version, so I think it is very small change.

**Comment by doichanj** [comment]
I temporary delete MPI implementations, now it only supports GPUs.
And I also deleted 2 derived classes and now there is only one derived class (QubitVectorPar) from the original version. 
I modified CMakeList.txt to detect if there is CUDA installed or not and if there is, it automatically build GPU version of state vector simulator.

**Comment by chriseclectic** [comment]
Superseded by #363

**Pull request closed without merging**
