### PR TITLE
Raise Qiskit dependency to 0.45.0

### PR DESCRIPTION
**Pull request by doichanj**
### Summary
This is fix for issue #2007 

### Details and comments
Aer imports `qiskit.circuit.library.DiagonalGate` for name mapping and it requires Qiskit >= 0.45.0

### CODE REVIEW

**Review by hhorii — APPROVED** [review]
LGTM

**Comment by satyardn** [comment]
I have got Qiskit 1.0.0 and the Aer package is not supported. Any help?

**Comment by jakelishman** [comment]
Aer 0.13.3 should work with Qiskit 1.0 - do you have an up-to-date version of Aer?

**Comment by jakelishman** [comment]
Please can you open an issue and provide details of the error messages, and all the versions of relevant tools?

**Pull request merged**
