### PR TITLE
Noise transformation with new channel interface

### PR DESCRIPTION
**Pull request by gadial**

### CODE REVIEW

**Comment by chriseclectic** [comment]
@gadial overall looks good (@atilag do you want to review code in more detail?)

A couple of organisational changes:

* Could you create a folder in `aer.noise` called `utils` and move the `noise_transformations.py` file there and add an `__init__.py` file to that folder containing:

```python
from .noise_transformation import NoiseTransformer
from .noise_transformation import approximate_quantum_error
from .noise_transformation import approximate_noise_model
```

* update the `__init__.py` file in `aer.noise` to add `from . import utils`
* Add a short description at the end of doc string of the `noise.__init__.py`  containing a short description like:

```
Noise Utilities
--------------
The `noise.utils` module contains utilities for noise models and errors including:
    <briefly describe the approximation functions and noise transformer>
```

**Comment by chriseclectic** [comment]
I noticed a bug in trying it out: currently it seems to leave a lot of operators as type `"kraus"` when using `reset` or `clifford` approximation methods (which means they won't be able to be run on the stabilizer qasm simulator). For example if I have a kraus error `error = amplitude_damping_error(0.3)`, then:

* `approximate_quantum_error(error, operator_string='reset')._noise_circuits` returns

```python
[[{'name': 'id', 'qubits': [0]}],
 [{'name': 'kraus', 'qubits': [0], 'params': [array([[1, 0],
           [0, 0]]), array([[0, 1],
           [0, 0]])]}],
 [{'name': 'kraus', 'qubits': [0], 'params': [array([[0, 0],
           [0, 1]]), array([[0, 0],
           [1, 0]])]}]]
```
where it should probably be
```python
[[{'name': 'id', 'qubits': [0]}],
 [{'name': 'reset', 'qubits': [0]}],
 [{'name': 'reset', 'qubits': [0]}, {'name': 'x', 'qubits': [0]}]]
```

* `approximate_quantum_error(error, operator_string='clifford')._noise_circuits` returns:

```python
[[{'name': 'id', 'qubits': [0]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([1., 0.]), array([0., 1.])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([1.+0.j, 0.+0.j]), array([0.+0.j, 0.+1.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([1.+0.j, 0.+0.j]), array([0.+0.j, 0.-1.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([1.+0.j, 0.+0.j]), array([ 0.+0.j, -1.+0.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j, 0.70710678+0.j]),
    array([ 0.70710678+0.j, -0.70710678+0.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j, 0.70710678+0.j]),
    array([-0.70710678+0.j,  0.70710678+0.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([ 0.70710678+0.j, -0.70710678+0.j]),
    array([0.70710678+0.j, 0.70710678+0.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j, 0.70710678+0.j]),
    array([0.+0.70710678j, 0.-0.70710678j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j        , 0.        +0.70710678j]),
    array([0.70710678+0.j        , 0.        -0.70710678j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j, 0.70710678+0.j]),
    array([0.-0.70710678j, 0.+0.70710678j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j        , 0.        -0.70710678j]),
    array([0.70710678+0.j        , 0.        +0.70710678j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j        , 0.        +0.70710678j]),
    array([0.        +0.70710678j, 0.70710678+0.j        ])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j        , 0.        -0.70710678j]),
    array([ 0.        +0.70710678j, -0.70710678+0.j        ])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([ 0.70710678+0.j, -0.70710678+0.j]),
    array([0.+0.70710678j, 0.+0.70710678j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j        , 0.        +0.70710678j]),
    array([ 0.        -0.70710678j, -0.70710678+0.j        ])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j        , 0.        -0.70710678j]),
    array([0.        -0.70710678j, 0.70710678+0.j        ])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([ 0.70710678+0.j, -0.70710678+0.j]),
    array([0.-0.70710678j, 0.-0.70710678j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j        , 0.        +0.70710678j]),
    array([-0.70710678+0.j        ,  0.        +0.70710678j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.70710678+0.j        , 0.        -0.70710678j]),
    array([-0.70710678+0.j        ,  0.        -0.70710678j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([ 0.70710678+0.j, -0.70710678+0.j]),
    array([-0.70710678+0.j, -0.70710678+0.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.+0.j, 1.+0.j]), array([1.+0.j, 0.+0.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.+0.j, 0.-1.j]), array([0.+1.j, 0.+0.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.+0.j, 0.+1.j]), array([1.+0.j, 0.+0.j])]}],
 [{'name': 'kraus',
   'qubits': [0],
   'params': [array([0.+0.j, 0.-1.j]), array([1.+0.j, 0.+0.j])]}]]
```

**Comment by gadial** [comment]
> I noticed a bug in trying it out: currently it seems to leave a lot of operators as type `"kraus"` when using `reset` or `clifford` approximation methods

This was indeed a bug. Now when possible the algorithm outputs "unitary". I'll try to improve it further so that it corresponds to your description, but even in the current state it should be applicable to Clifford simulation.

**Comment by gadial** [comment]
The rest of the issues were handled.

**Comment by chriseclectic** [comment]
@gadial could you rebase against master to clean up the git history?

The fix now returns `"unitary"` instructions, however these still cant be simulated by the stabilizer simulator unless they are converted into standard qobj instructions. You can do this by using the function `noise.errors.errorutils.standard_gate_instruction` which will do this conversion for single-qubit cliffords (I extended it in PR #154 to covert the reset Kraus too):

To use my previous example:

```python
from qiskit.providers.aer import noise
from qiskit.providers.aer.noise.errors import errorutils

error = noise.errors.amplitude_damping_error(0.2)
approx_reset = noise.utils.approximate_quantum_error(error, operator_string='reset')._noise_circuits
approx_cliff = noise.utils.approximate_quantum_error(error, operator_string='Clifford')._noise_circuits
```

You can see how this conversion should work as:
```python
for circ in approx_reset._noise_circuits:
    for instr in circ:
        print(errorutils.standard_gate_instruction(instr, ignore_phase=True))
[{'name': 'id', 'qubits': [0]}]
[{'name': 'reset', 'qubits': [0]}]
[{'name': 'reset', 'qubits': [0]}, {'name': 'x', 'qubits': [0]}]
```

and 

```python
for circ in approx_cliff._noise_circuits:
    for instr in circ:
        print(errorutils.standard_gate_instruction(instr, ignore_phase=True))
[{'name': 'id', 'qubits': [0]}]
[{'name': 'id', 'qubits': [0]}]
[{'name': 'sdg', 'qubits': [0]}]
[{'name': 's', 'qubits': [0]}]
[{'name': 'z', 'qubits': [0]}]
[{'name': 'h', 'qubits': [0]}]
[{'name': 'h', 'qubits': [0]}, {'name': 'z', 'qubits': [0]}]
[{'name': 'z', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}]
[{'name': 'h', 'qubits': [0]}, {'name': 'sdg', 'qubits': [0]}]
[{'name': 'sdg', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}]
[{'name': 'h', 'qubits': [0]}, {'name': 's', 'qubits': [0]}]
[{'name': 's', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}]
[{'name': 'sdg', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}, {'name': 'sdg', 'qubits': [0]}]
[{'name': 's', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}, {'name': 'sdg', 'qubits': [0]}]
[{'name': 'z', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}, {'name': 'sdg', 'qubits': [0]}]
[{'name': 'sdg', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}, {'name': 's', 'qubits': [0]}]
[{'name': 's', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}, {'name': 's', 'qubits': [0]}]
[{'name': 'z', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}, {'name': 's', 'qubits': [0]}]
[{'name': 'sdg', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}, {'name': 'z', 'qubits': [0]}]
[{'name': 's', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}, {'name': 'z', 'qubits': [0]}]
[{'name': 'z', 'qubits': [0]}, {'name': 'h', 'qubits': [0]}, {'name': 'z', 'qubits': [0]}]
[{'name': 'x', 'qubits': [0]}]
[{'name': 'y', 'qubits': [0]}]
[{'name': 'sdg', 'qubits': [0]}, {'name': 'x', 'qubits': [0]}]
[{'name': 's', 'qubits': [0]}, {'name': 'x', 'qubits': [0]}]
```

which are `QuantumErrors` which are compatible with `"method": "stabilizer"` for the qasm simulator.

**Comment by gadial** [comment]
I have fixed the Kraus/Unitary problem, but I am not able to clean the PR history using rebasing. I've opened a clean PR at #162 and hopefully this will be the last of it.

**Pull request closed without merging**
