### PR TITLE
Implemented ecr for stabilizer simulator.

### LINKED ISSUE #1883: Add 2-qubit Clifford gate ECR in the stabilizer simulator (Clifford simulator)
### What is the expected behavior?

Add 2-qubit ECR gate, which is a Clifford gate, to the stabilizer simulator (Clifford simulator). Newer IBM devices have ECR as the 2-qubit basis gate. Thus, it is better to have the gate in the stabilizer simulator as well.

### PR DESCRIPTION
**Pull request by MarcMaussner**
### Summary
fixes #1883 

### Details and comments
Implemented ecr gate for aer_stabilizer_simulator.

### CODE REVIEW

**Review by doichanj — CHANGES_REQUESTED** [review]
Could you add test case for ECR gate in `test/terra/backends/test_cliffords.py` and `test/terra/reference/ref_2q_clifford.py`

**Comment by doichanj** [comment]
Please format the codes by `tox -eclang-format`

**Comment by doichanj** [comment]
Test code still has style issue, please refer to https://github.com/Qiskit/qiskit-aer/blob/main/CONTRIBUTING.md#style-and-lint and fix it.

**Comment by MarcMaussner** [comment]
Failing test is not regarding code change, it's in "test_run_path_with_more_params_than_expressions" where 397 != 500 with delta 100. How to proceed?

**Review by doichanj — APPROVED** [review]

**Pull request merged**
