### PR TITLE
Enhancement of multi-controlled gates

### PR DESCRIPTION
**Pull request by yaelbh**
- Added tests to `mcx` and `mcphase`.
- A couple of small fixes for `mcphase`.
- Added support to `mcx_gray` in the statevector simulator. This is what the simulator gets in the `qobj` for circuits containing the `mcx` gate.

### CODE REVIEW

**Comment by yaelbh** [comment]
Still need to update unitary and statevector.

**Comment by yaelbh** [comment]
@vvilpas  CI is failing - why is taking so long on Windows?

**Comment by yaelbh** [comment]
Conflicts are resolved, this is ready

**Review by vvilpas — APPROVED** [review]
LGTM!

**Pull request merged**
