### PR TITLE
Comment derivation depolarising probability from gate error

### PR DESCRIPTION
**Pull request by fanizzamarco**
### Summary
p_depol = (dim) * gate_error / (dim-1) should not be instead
p_depol = (dim-1) * gate_error / dim ? 
I changed it but the other formulas should be also corrected

### CODE REVIEW

**Comment by chriseclectic** [comment]
Hi @fanizzamarco, thanks for checking this. I just rechecked the calculation and I believe it's correct:

The depolarizing channel probability in Aer is defined as `E_dep = (1-p) * I +  p * D` where `I` is the identity channel and `D` is the completely depolarizing channel (`D(rho) = id / d`)

The gate error is the average gate infidelity `e = 1 - F`. 

For the depolarizing channel we have:

```
F(E_dep) = (1 - p) * F(I) + p * F(D) 
         = (1 - p) * 1 + p * (1 / d)    # F(I) = 1, F(D) = 1/d
         = 1 - p * (d - 1) / d
=> p = (1 - F(E_dep)) / ((d - 1) / d) 
     = d * (1 - F(E_dep)) / (d - 1)
     = d * e / (d - 1)
```
Hence for `d=2` if all gate error is due to the depolarizing channel we have `p_depol = 2 * gate_error`

Maybe you could update your PR with the more complete derivation in the code comments and we could merge that?

**Comment by fanizzamarco** [comment]
> Hi @fanizzamarco, thanks for checking this. I just rechecked the calculation and I believe it's correct:
> 
> The depolarizing channel probability in Aer is defined as `E_dep = (1-p) * I + p * D` where `I` is the identity channel and `D` is the completely depolarizing channel (`D(rho) = id / d`)
> 
> The gate error is the average gate infidelity `e = 1 - F`.
> 
> For the depolarizing channel we have:
> 
> ```
> F(E_dep) = (1 - p) * F(I) + p * F(D) 
>          = (1 - p) * 1 + p * (1 / d)    # F(I) = 1, F(D) = 1/d
>          = 1 - p * (d - 1) / d
> => p = (1 - F(E_dep)) / ((d - 1) / d) 
>      = d * (1 - F(E_dep)) / (d - 1)
>      = d * e / (d - 1)
> ```
> Hence for `d=2` if all gate error is due to the depolarizing channel we have `p_depol = 2 * gate_error`
> 
> Maybe you could update your PR with the more complete derivation in the code comments and we could merge that?

Great, sorry for having used your time! I exchanged the definitions, and my confusion came from the fact that there is no warning on gate_error in the calculation of p_depol, and it could come out p_depol>1. But the code works perfectly then, since p_depol is checked afterwards. Thank you very much for your effort!

**Comment by fanizzamarco** [comment]
Now that I understand how this works, I still have a doubt on the last formula... When the relaxation times go to infinity p_depol should go to the value that we have already checked. It seems that this does not hold for the last formula

```
denom = (q0_par1 + q1_par1 + q0_par1 * q1_par1 +
             4 * q0_par2 * q1_par2 +
             2 * (q0_par2 + q1_par2) +
             2 * (q1_par1 * q0_par2 + q0_par1 * q1_par2))
    p_depol = 1 + (5 / 3) * (4 * gate_error - 3) / denom
```
when q0_par1=1,q0_par2=1,... denom=15, so maybe it is
p_depol = 1 + (5 ) * (4 * gate_error - 3) / denom
so that when denom=15, p_depol=4/3 *gate_error. Moreover, when gate_error=zero and denom=15, p_depol=1/3, while it should be zero.
sorry if I am misunderstanding again

**Comment by chriseclectic** [comment]
Yes, good catch! The correct formula should indeed be

```python
p_depol = 1 + 5 * (4 * gate_error - 3) / denom
```

**Comment by fanizzamarco** [comment]
Corrected!

**Comment by chriseclectic** [comment]
Thanks @fanizzamarco !

**Pull request merged**
