### PR TITLE
Fixed the tests and the revealed bugs

### PR DESCRIPTION
**Pull request by yaelbh**
### Summary

As explained in #1021, because of a bug in the tests, some tests were not running until now. This PR fixes the bug. Then, some of the now running tests fail. This PR fixes the bugs that cause this failure.

### Details and comments

The fixes:
- A fix in the test, as described in #1021.
- Added `sx` to the list of gates for MPS, solving a test that fails while complaining that `sx` is invalid for MPS.
- Fixed places where function parameters were not passed correctly.

### CODE REVIEW

**Comment by yaelbh** [comment]
The item "Fixed places where function parameters were not passed correctly" resolves #1022

**Comment by yaelbh** [comment]
The PR can't be merged because of test failures that are not related to it (in density matrix gpu thrust)

**Comment by chriseclectic** [comment]
@yaelbh I added a fix for the density matrix tests and a release note. Can you add a line for any other bug fixes (other than adding sx gate) you made to the release note?

**Comment by yaelbh** [comment]
@chriseclectic I've updated the release notes: added a line for a bug, and rephrased the line about the `sx` gate.

**Comment by chriseclectic** [comment]
Thanks @yaelbh. For release notes its not necessary to go into too much detail about the C++ source code since they are more for qiskit Python users to know what is added / fixed / changed etc wrt to the python module (ie how the bug effected users of the python code)

**Review by chriseclectic — APPROVED** [review]

**Pull request merged**
