### PR TITLE
fix a bug in multiple_chunk_required

### PR DESCRIPTION
**Pull request by hhorii**
### Summary

Throw an error if memory is short

### Details and comments

Since multi-chunk was introduced, mulit-chunk is enabled if memory is short because of following code:

```
bool Controller::multiple_chunk_required(const Circuit &circ,
                                const Noise::NoiseModel &noise) const
{
  if(circ.num_qubits < 3)
    return false;

  if(num_process_per_experiment_ > 1 || Controller::get_min_memory_mb() < required_memory_mb(circ, noise))
    return true;

  if(cache_block_qubit_ >= 2 && cache_block_qubit_ < circ.num_qubits)
    return true;

  return false;
}
```

The second branch condition enable multi-chunk if a number of processes is two or more **OR** local memory is smaller than required memory for state.
This PR changes this **OR** with **AND**.

This PR will resolve https://github.com/Qiskit/qiskit-aer/issues/1260.

### CODE REVIEW

**Review by chriseclectic — COMMENTED** [review]
LGTM. Can you add a short release note for the the bug fix?

**Comment by doichanj** [comment]
Second branch should be separated to select multi-chunk mode when using GPU method. 
The code is like this. 

```
bool Controller::multiple_chunk_required(const Circuit &circ,
                                         const Noise::NoiseModel &noise) const 
{
  if (circ.num_qubits < 3)
    return false;
  if (cache_block_qubit_ >= 2 && cache_block_qubit_ < circ.num_qubits)
    return true;

  if(num_process_per_experiment_ == 1 && sim_device_ == Device::GPU){
    return (max_gpu_memory_mb_ / num_gpus_ < required_memory_mb(circ, noise));
  }
  if(num_process_per_experiment_ > 1){
    size_t total_mem = max_memory_mb_;
    if(sim_device_ == Device::GPU)
      total_mem += max_gpu_memory_mb_;
    if(total_mem*num_process_per_experiment_ > required_memory_mb(circ, noise))
      return true;
  }

  return false;
}
```

**Comment by hhorii** [comment]
@doichanj The above code works in aer_controller.hpp but not in controller.hpp that does not have `sim_device_ `.  Instead of `sim_device_ == Device::GPU`, 3bfe7b5 uses `cache_block_qubit_ >= 2`.

**Comment by doichanj** [comment]
I think it is enough for controller.hpp

**Review by chriseclectic — APPROVED** [review]

**Pull request merged**
