### PR TITLE
Changed usage of == for floating point comparison to Linalg::almost_equal in svd.cpp

### PR DESCRIPTION
**Pull request by merav-aharoni**
### Summary
Changed usage of `==` and `!=` for floating point comparison to `Linalg::almost_equal` in svd.cpp.

### Details and comments
1. Used casting to `long double` for all comparisons, to get sufficient precision 
2. Changed some constant values in the code to `#define`
3. Fixed indentation to more standard format

This PR resolves issue #468.

### CODE REVIEW

**Comment by atilag** [comment]
Thanks @merav-aharoni ! 
Test are failing because I think we have changes the `Result` object. Will try to fix this and merge!

**Comment by merav-aharoni** [comment]
@atilag , thanks for letting me know, because I was just trying to figure out how I would run this on Windows, because my usual platform in Linux.

**Comment by chriseclectic** [comment]
Is quadruple precision of `long double` required?

**Comment by merav-aharoni** [comment]
@chriseclectic , unfortunately it is needed. At first I tried using double, but I had failures. Also in the code itself, there is a place where I resorted to cast to `long double` when I find that double precision is not sufficient to detect the difference between a very small number and 0. This works fine on Linux, but I think Windows does not support `long double`. Any suggestions?

**Comment by atilag** [comment]
So the problem is that Microsoft Visual Studio compiler treats `double` and `long double` as the same type... it's not a bug, the standard allows this. I don't really know what other options we have for Windows at the moment... will investigate further.

**Pull request closed without merging**
