### PR TITLE
3-qubit testing and a minor bug fix

### PR DESCRIPTION
**Pull request by haggaila**
### Summary
Fixed issue #526 and added some tests of the open pulse simulator, comparing the evolution of a 3-qubit Hamiltonian with 60 random driven terms (corresponding to all 4 * 4 * 4 Pauli products, minus the trivial drifts).

### CODE REVIEW

**Comment by chriseclectic** [comment]
@haggaila can you rebase this PR against master now that we have merged the openpulse-sim branch

**Comment by haggaila** [comment]
Added three new test functions that currently fail - there is one exception, and two other fails are unexplained or against what I expect (or I may be misusing the simulator).

**Comment by DanPuzzuoli** [comment]
@haggaila I've just copied your changes locally and am playing around with things. I've found:

- For `test_3Q_X_drift`, I'm actually getting values of `nan` in the returned vector, regardless of the value of `h_abc`. Can you track this down?
- In the truncation tests: no truncation is occurring as you need to pass `qubit_list` when calling `HamiltonianModel.from_dict`. This admittedly is somewhat odd behaviour, as you're passing `qubit_list` to the `PulseSystemModel` constructor, so ideally the truncation could happen here as well. However, due to the peculiarities of the parsing, we're currently treating `HamiltonianModel` as being immutable, so for now just pass `qubit_list` when constructing the Hamiltonian. However, this also produces an error: as the identities are included in the Hamiltonian string in every term in the Hamiltonian you are constructing, the parser thinks every qubit is involved in every Hamiltonian term, so it drops every term when parsing without a full qubit list, returning an empty `system`, which causes further errors. I think that you will need to modify the string to not have identity terms for this truncation to work. Once this is done though, the tests will still return an error, due to vector dimension issues. You'll need to set the initial state for the simulator to be of the appropriate dimension given the truncation. Also, I think it would be good for the test to compare the output state to the expected vector assuming the truncation/simulation has been done correctly (as opposed to checking that it is different from what would happen with no truncation).
- For the 3Q

**Comment by atilag** [comment]
@haggaila I merged with current `master` branch and there should be no conflicts anymore. 
What's the status of this PR? Could you address/discuss @DanPuzzuoli comments?
Thanks!! :)

**Comment by haggaila** [comment]
Thanks @atilag, this was discussed and solved offline, and as you say should already have been corrected in master.

**Pull request closed without merging**
