### PR TITLE
Speed up assembling of noise model for circuits without delays

### LINKED ISSUE #1407: Performance regression in noise model loading for Qiskit Aer 0.10.0
### Informations

- **Qiskit Aer version**: 0.10.0
- **Python version**: 3.7
- **Operating system**: MacOS

### What is the current behavior?

The performance of simulations with large noise models greatly decreased in Aer 0.10.0 This is worst for FakeBackend simulators for large number of qubit devices since they have a lot of error terms in their noise models. 

### Steps to reproduce the problem

```python
from qiskit import QuantumCircuit
from qiskit.providers.aer import AerSimulator
from qiskit.test.mock import FakeParis

# 27-qubit fake backend simulator
backend = AerSimulator.from_backend(FakeParis())

# 1-qubit circuit
circ = QuantumCircuit(1)
circ.x(0)
circ.measure_all()

# Run sim
%timeit result = backend.run(circ).result()
```

Times on 0.9.1
```
%timeit result = backend.run(circ).result()
11.8 ms ± 3.51 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Times on 0.10.0
```
%timeit -r 3 result = backend.run(circ).result()
16.5 s ± 84.6 ms per loop (mean ± std. dev. of 3 runs, 1 loop each)
```

This is about a 1000x slowdown to `run`

### Suggested solutions

After some debugging I believe this is due to #1141 which changed `QuantumError` instructions to use `QuantumCircuit` internally instead of qobj.

The assembly of these circuits to qobj is now being called through the C++ pybind code and has a huge overhead. Doing this before calling the C++ code via calling `noise_model.to_dict` as part of run also results in big overhead. 

Oddly this issue also only seems to effect some version of python, particularly 3.7 which may be due to how assemble is implemented wrt python multiprocessing.

So far I've managed to largely fix the problem by manually assemble quantum errors and bypassing the terra assemble function using
```python
instructions = [[op[0].assemble().to_dict() for op in circ.data for circ in self._circs]
```
instead of current
```python
qobj = assemble(self.circuits)
instructions = [exp.to_dict()['instructions'] for exp in qobj.experiments]
```

With this change I get

```
%timeit result = backend.run(circ).result()
331 ms ± 4.21 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

### PR DESCRIPTION
**Pull request by itoko**
### Summary
The commit fixes the remaining minor performance issue introduced at #1391 by skipping the run of noise pass manager for circuits without delays.

Fixes #1407 (performance regression) completely in addition to the major fix #1408.

### CODE REVIEW

**Comment by itoko** [comment]
I've confirmed that this PR significantly reduces the assemble time of noisy simulation of circuits without delays.

Without this PR:
TRANSPILE TIME TAKEN: 66.19
ASSEMBLE TIME TAKEN: 5.05
RUN QOBJ TIME TAKEN: 6.21

With this PR:
TRANSPILE TIME TAKEN: 63.55
ASSEMBLE TIME TAKEN: 1.17
RUN QOBJ TIME TAKEN: 6.41

Using the following code
```
import time
import numpy as np
from qiskit_experiments.library import StandardRB
from qiskit.providers.aer import AerSimulator
from qiskit.test.mock import FakeParis

backend = AerSimulator.from_backend(FakeParis())

start = time.time()
lengths = np.arange(1, 1000, 100)
num_samples = 10
seed = 1010
qubits = [0]

# Run an RB experiment on qubit 0
exp = StandardRB(qubits, lengths, num_samples=num_samples, seed=seed)

# Step by step
from qiskit import transpile

# Generate and transpile circuits
start = time.time()
circuits = transpile(exp.circuits(), backend)
stop = time.time()
print("TRANSPILE TIME TAKEN: {:.2f}".format(stop - start))

# Simulator Assemble
start = time.time()
qobj = backend._assemble(circuits)
stop = time.time()
print("ASSEMBLE TIME TAKEN: {:.2f}".format(stop - start))

# Simulator Run
start = time.time()
result = backend._run(qobj)
stop = time.time()
print("RUN QOBJ TIME TAKEN: {:.2f}".format(stop - start))
```

**Review by jakelishman — COMMENTED** [review]
This looks fine to me, but #1409 also has the same optimisation, but with less data iteration due to a new data structure it introduces.  I think #1409 likely supersedes this.

**Review by chriseclectic — COMMENTED** [review]
As @jakelishman said this is already covered by #1409 which includes this fix along with a fixes for other unnecessary iteration from qasm3 compiling, qerror_loc insertion, and qobj splitting.

**Comment by itoko** [comment]
Close as it's already covered by #1409

**Pull request closed without merging**
