### PR TITLE
Rewrite stabilizer snapshot_probabilities

### PR DESCRIPTION
**Pull request by yaelbh**
### Summary

The code for the stabilizer probabilities snapshot does not work properly for subsets of qubits. This pull request fixes this.

### Details and comments

More details can be found in https://github.com/Qiskit/qiskit-aer/issues/389

### CODE REVIEW

**Comment by yaelbh** [comment]
@atilag There are several locations in this code, including in this pull request, where the assignment operator is used for qubit registers (i.e. statevector data structure), assuming that it performs a deep copy. This is indeed a deep copy, since the data structure does not contain pointer, at least currently. But I don't think it is a good practice to use an assignment operator that was not implemented explicitly. What do you think?

**Comment by yaelbh** [comment]
Ready for review  @chriseclectic.   I'll continue from here with the expectation value snapshot.

**Comment by yaelbh** [comment]
Pauli expval snapshot for stabilizer is now included and ready for review. Thanks to @ShellyGarion for advise. @chriseclectic

**Comment by chriseclectic** [comment]
@yaelbh can you add a line to the changelog that you added support for probability and pauli expval snapshots to stabilizer method

**Comment by yaelbh** [comment]
@chriseclectic Done

**Pull request merged**
