### PR TITLE
Removing usage of the deprecated U1Gate from parallel processing examples.

### LINKED ISSUE #1532: Parallel.rst using deprecated method to apply gates
Currently in `docs/apidocs/parallel.rst` the U gates are applied as `circ.u1(pi/2,2)` and `circ2.u1(pi/2,2)` which flags a warning that this method is deprecated as of 0.16.0. 

The fix should be using the circuit library (https://qiskit.org/documentation/apidoc/circuit_library.html) and 

```
from qiskit.circuit.library import U1Gate
...
gate = U1Gate(pi/2)
...
circ.append(gate, [2])
...
circ2.append(gate,[2])
```

### PR DESCRIPTION
**Pull request by upsideon**
### Summary

Fixes #1532 by replacing usage of the `U1Gate` with usage of the `PhaseGate`.

### CODE REVIEW

**Review by jakelishman — APPROVED** [review]
Thanks!  Good job thinking about the release note - we actually don't usually write them for documentation-only changes, but it's good that you'd thought about it.

**Comment by upsideon** [comment]
@jakelishman It seems that the build for the most recent commit failed with the following error messages:

```
ERROR: qiskit_aer-0.11.0-cp37-cp37m-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
Error: Command ['pip', 'install', '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibuildwheel5f4pmz88/repaired_wheel/qiskit_aer-0.11.0-cp37-cp37m-macosx_11_0_x86_64.whl'] failed with code 1. None
```
Is this a known issue that occurs sporadically on builds and could be resolved with a restart?

**Comment by jakelishman** [comment]
No need to worry - it's a problem in our build process right now, which'll be fixed by #1536.

**Comment by upsideon** [comment]
Ah, okay. Thank you!

**Pull request merged**
