### PR TITLE
Release 0.10.4

### PR DESCRIPTION
**Pull request by hhorii**
### Summary

Release 0.10.4 to fix bugs.

### Details and comments

- [x] include #1436

### CODE REVIEW

**Comment by mtreinish** [comment]
Just marking as on hold until all the required PRs to main are merged and then backported as part of this PR

**Comment by hhorii** [comment]
#1480 and #1482 are for stable-backport-potential. #1480 can be merged but #1482 is not because it depends on #1400 and #1489.

**Comment by hhorii** [comment]
Running test in advance. [d3b73ea](https://github.com/Qiskit/qiskit-aer/pull/1481/commits/d3b73eadda6aa1491911b7c8719d6ca63c3b0dc3) will be taken once #1496 is merged.

**Comment by mtreinish** [comment]
It looks like the test failures are real I expect that #1496 is causing a segfault or similar error causing linux and macos to fail on:
`test.terra.backends.aer_simulator.test_noise.TestNoise.test_kraus_gate_noise_on_QFT_cache_blocking_2___statevector____Thrust__`

**Comment by hhorii** [comment]
> It looks like the test failures are real I expect that #1496 is causing a segfault or similar error causing linux and macos to fail on: `test.terra.backends.aer_simulator.test_noise.TestNoise.test_kraus_gate_noise_on_QFT_cache_blocking_2___statevector____Thrust__`

Another possibility is that thrust performance issue resolved in #1497 (via #1498) produces timeout. But, yes, #1496 is necessary for this release, I think.

**Comment by mtreinish** [comment]
#1498 wasn't intended for backport, it makes an incompatible change in the supported environment for 0.10.x. We should still be building with manylinux2010 for 0.10.x which is what #1499 did. We definitely need to include #1497 here though.

**Comment by hhorii** [comment]
> #1498 wasn't intended for backport, it makes an incompatible change in the supported environment for 0.10.x. We should still be building with manylinux2010 for 0.10.x which is what #1499 did. We definitely need to include #1497 here though.

I reverted #1498 and cherry-picked #1497.

**Comment by mtreinish** [comment]
Thanks, this LGTM. I think we just need to backport #1501 now and then I think we are ready to release

**Review by mtreinish — APPROVED** [review]

**Pull request merged**
