### PR TITLE
WIP: add tests for MCX gate (4-qubit)

### PR DESCRIPTION
**Pull request by ivanightingale**
### Summary
To fix one of the items in #132 .

### Details and comments
Adds tests and test reference for MCX gate (4-qubit).

### CODE REVIEW

**Comment by ivanightingale** [comment]
Hi @chriseclectic I've added deterministic qasm tests for MCX gates (4-qubit), basically in the same fashion as CCX tests were implemented. Could you please take a quick look and let me know if I'm going the right direction?

**Comment by yaelbh** [comment]
Hi @ivanightingale. This is definitely the right direction. A few small comments:
1. I think you can add calls to this test also in `test_qasm_simulator_matrix_product_state` and `test_unitary_simulator`.
2. I recommend that in your environment you add debug prints to verify that all the simulation methods that you want to cover really run in the test.
3. I  have a suggestion for a general change in the non-Clifford tests. I'll open an issue for it. Please go ahead and continue with this pull request as it is, since it's independent of the issue that I'll open.

**Comment by ivanightingale** [comment]
Hi @yaelbh , thanks for the feedbacks! I haven't added all the necessary tests yet (like the ones you mentioned) but I'll do them next since now I know I'm on the right track. I'll let you know when the pr is ready for review.

**Comment by yaelbh** [comment]
Tests for multi-control gates were recently added in `qasm_standard_gates.py`. The file `qasm_noncliffords.py` has be removed, and `qasm_cliffords.py` tests only the stabilizer simulator. Therefore this pull request can be closed.

**Pull request closed without merging**
