### PR TITLE
Remove python37 GitHub action

### PR DESCRIPTION
**Pull request by hhorii**
### Summary

This PR follows #1819. If my PR to tungbq:remove-python37-github-action is merged, I will close this PR.

### CODE REVIEW

**Comment by hhorii** [comment]
Hmm, I'm not able to send a PR to tungbq:remove-python37-github-action ...
@tungbq if possible, could you cherry-pick a2a1a28 into your branch?

**Comment by tungbq** [comment]
> Hmm, I'm not able to send a PR to tungbq:remove-python37-github-action ... @tungbq if possible, could you cherry-pick [a2a1a28](https://github.com/Qiskit/qiskit-aer/commit/a2a1a2827f8a3be548a74f176f811c5a1c7a733a) into your branch?

@hhorii It's done on my PR. I've added new commit https://github.com/Qiskit/qiskit-aer/pull/1819/commits/caa54ddde5885e485cd7db48c06ca39779e5916a follow your commit.

**Comment by hhorii** [comment]
@tungbq thanks. but I found that there is another problem in Aer's CI. Once the problem is resolved, I may ask other changes to your PR. Please give few days to identify the root cause.

**Comment by hhorii** [comment]
@tungbq db64500 restores the CI. Could you cherry-pick it on your branch?

**Comment by tungbq** [comment]
> @tungbq [db64500](https://github.com/Qiskit/qiskit-aer/commit/db6450062415a33f71a0b578f6a4f0dac543b301) restores the CI. Could you cherry-pick it on your branch?

@hhorii It's done in my latest commit: https://github.com/Qiskit/qiskit-aer/pull/1819/commits/f74d5ddb6786a2dd0995d6b9e97a3c5672e1dd50

**Comment by hhorii** [comment]
#1819 followed this PR.

**Pull request closed without merging**
