### PR TITLE
Make vector allocation aligned to 64-bytes

### PR DESCRIPTION
**Pull request by sfantao**
### Summary
Make vector allocation aligned to 64-bytes as that is the same alignment requirement used by QubitVector data.

### Details and comments
`AER::Vector` is in some cases used to initialize `QubitVector` data and the code assumes that that storage is at least 32-byte aligned so that mm256 instructions can be used. This PR makes `AER::Vector` storage have the same alignment requirements (64-byte) as `QubitVector` so that one doesn't get into segfaults when trying to access this storage with vector intrinsics.

This fixes https://github.com/Qiskit/qiskit-aer/issues/1908.

### CODE REVIEW

**Review by doichanj — APPROVED** [review]

**Review by doichanj — CHANGES_REQUESTED** [review]
Please add release note for this fix

**Comment by sfantao** [comment]
Added release note for the fix.

**Comment by sfantao** [comment]
@doichanj , can you help understand how this PR is breaking the Windows builds? It shouldn't change anything there. I only see the compiler running out of memory.

**Comment by doichanj** [comment]
Windows build sometimes fails because of heap memory shortage. Only we can do is to rerun until it will not fail

**Review by doichanj — APPROVED** [review]

**Pull request merged**
