### PR TITLE
Initialize gate

### PR DESCRIPTION
**Pull request by yaelbh**
### Summary

This is a continuation of #117

### CODE REVIEW

**Comment by yaelbh** [comment]
I see two tasks:
- [ ] Write tests for `qasm_simulator`, similar to tests of `reset` there.
- [ ] Handle correctly in `check_measure_sampling_opt`, namely do not optimize in the presence of `initialize` operations. Similarly update `is_measure_or_reset` to be `true` also for `initialize`.

I don't understand why Terra needs on its side to reset before the initialization, as this is done by the simulator as part of the initialization process.

**Comment by yaelbh** [comment]
Note that Travis will not pass because Terra and Aer are out of sync. Need to checkout Terra f6cfde67f1c.

**Comment by chriseclectic** [comment]
@yaelbh if you rebase from master it should pass now. I've merged shellys PR so you can squash/drop those commits and just add your additions/changes.

**Comment by yaelbh** [comment]
Ready.
In `noise_model.hpp` there is a special handling of the case where the gate is `measure` or `reset` (`is_measure_or_reset`). It looks like the handling should be for any multiple qubit gate, including `initialize` but not only. I did not change the code there.

**Comment by chriseclectic** [comment]
@yaelbh great! I would say "initialize" doesn't really need to be handled by noise model because if you were trying to mimic noise in a device you should unroll the initialise to a reset and preparation gates which would have the noise model defined on them.

**Pull request merged**
