### PR TITLE
Allow for suppressing warnings in NoiseModel.from_backend()

### PR DESCRIPTION
**Pull request by nonhermitian**
### Summary
The larger devices always have one or more bad gates that trigger warnings.  This allows for suppressing these.

### CODE REVIEW

**Comment by atilag** [comment]
One of the features we have with Python logging system, is that users can filter any Warning they want by doing:
```python
import logging
class WarningFilter(logging.Filter):
    def filter(self, record):
        return not record.getMessage().startswith('Device model')

logger = logging.getLogger("models")
logger.addFilter(WarningFilter())
```
This will filter all messages starting with "Device model" string, in the models.py file.
If you don't really mind about the warnings at all, you can just disable them:
```python
logging.disable(logging.WARNING)
```

**Comment by nonhermitian** [comment]
Ok.  But it is unclear what that has to do with the current PR that just extends similar functionality that is already in the code base, e.g.:

https://github.com/Qiskit/qiskit-aer/blob/1cff17f248c1a2ba556e1962dc3b5bd3b6437e65/qiskit/providers/aer/noise/noise_model.py#L398

https://github.com/Qiskit/qiskit-aer/blob/1cff17f248c1a2ba556e1962dc3b5bd3b6437e65/qiskit/providers/aer/noise/noise_model.py#L455

https://github.com/Qiskit/qiskit-aer/blob/1cff17f248c1a2ba556e1962dc3b5bd3b6437e65/qiskit/providers/aer/noise/noise_model.py#L465

https://github.com/Qiskit/qiskit-aer/blob/1cff17f248c1a2ba556e1962dc3b5bd3b6437e65/qiskit/providers/aer/noise/noise_model.py#L528

https://github.com/Qiskit/qiskit-aer/blob/1cff17f248c1a2ba556e1962dc3b5bd3b6437e65/qiskit/providers/aer/noise/noise_model.py#L540

https://github.com/Qiskit/qiskit-aer/blob/1cff17f248c1a2ba556e1962dc3b5bd3b6437e65/qiskit/providers/aer/noise/noise_model.py#L609

https://github.com/Qiskit/qiskit-aer/blob/1cff17f248c1a2ba556e1962dc3b5bd3b6437e65/qiskit/providers/aer/noise/noise_model.py#L654

https://github.com/Qiskit/qiskit-aer/blob/1cff17f248c1a2ba556e1962dc3b5bd3b6437e65/qiskit/providers/aer/noise/noise_model.py#L664

**Comment by nonhermitian** [comment]
Ok, now I see, the above does do what I need since I am an interested in using this in a module.    However, it still would be nice to extend the kwargs to allow suppressing the warnings without having to construct a whole class to do so.

**Comment by atilag** [comment]
So you pointed out to something that I call technical debt. We shall not couple logging behavior with function parameters, it does only increases coupling between these components and makes things harder to test.
This is the reason why loggers are singletons (unique global instances).

Ok, let's merge this if you find it useful.

**Pull request merged**
