### PR TITLE
Honor DISABLE_CONAN environment variable

### LINKED ISSUE #1079: Build: DISABLE_CONAN Env Var broken in qiskit-aer v0.7.2
### Informations

- **Qiskit Aer version**: 0.7.2
- **Python version**: 3.7.6
- **Operating system**: Linux

### What is the current behavior?

DISABLE_CONAN environment variable and CMake flag don't work as they should, and Conan dependencies are still searched.

### Steps to reproduce the problem

Build ``qiskit-aer v0.7.2`` with ``DISABLE_CONAN=1 python setup.py bdist_wheel`` from environment without conan.

Optional for full reproduction:
* Install Nix: ``curl -L https://nixos.org/nix/install | sh``
* ``nix-build -I nixpkgs=channel:nixos-20.03 -A python3Packages.qiskit-aer https://github.com/drewrisinger/nur-packages/archive/6c2e51c322fab401bbe4c597285710f643830cb3.tar.gz``

### What is the expected behavior?

This should build a wheel via skbuild/cmake without conan being present.
Instead, it seems the variable ``DISABLE_CONAN`` isn't set properly. See following trace:

Grep'd CMake build w/ ``--trace-expand`` flag on (note, this was with the partial solution below applied):
```
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/CMakeLists.txt(50):  if(DEFINED ENV{DISABLE_CONAN} )
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/CMakeLists.txt(51):  set(_DISABLE_CONAN_DEFAULT {DISABLE_CONAN} )
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/CMakeLists.txt(55):  option(DISABLE_CONAN Disable Conan package manager to find dependencies. If disabled, you must have all dependencies present on your system. {DISABLE_CONAN} )
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/CMakeLists.txt(57):  include(CTest )
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/.eggs/cmake-3.18.4.post1-py3.7-linux-x86_64.egg/cmake/data/share/cmake-3.18/Modules/CTest.cmake(50):  option(BUILD_TESTING Build the testing tree. ON )
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/.eggs/cmake-3.18.4.post1-py3.7-linux-x86_64.egg/cmake/data/share/cmake-3.18/Modules/CTest.cmake(54):  function(GET_VS_VERSION_STRING generator var )
--
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/CMakeLists.txt(139):  if(STATIC_LINKING )
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/CMakeLists.txt(149):  set(BACKEND_REDIST_DEPS  )
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/CMakeLists.txt(150):  setup_dependencies()
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/cmake/dependency_utils.cmake(16):  if(DISABLE_CONAN )
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/cmake/dependency_utils.cmake(18):  else()
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/cmake/dependency_utils.cmake(19):  include(conan_utils )
/tmp/nix-build-python3.7-qiskit-aer-0.7.2.drv-2/source/cmake/conan_utils.cmake(1):  include(conan )
```

Full build log:  https://gist.github.com/drewrisinger/de63a783861c28d14186714938e7029f

### Suggested solutions

Partial solution:
* Replace ``ENV{DISABLE_CONAN}`` variable read in ``CMakeLists.txt`` with proper syntax: ``$ENV{DISABLE_CONAN}``. Tested with this patch and it still didn't fix it. Ref (only second instance should be replaced): https://github.com/Qiskit/qiskit-aer/blob/1dbb97e21790c54a52d0faec9216935a730dfb53/CMakeLists.txt#L50-L54

### Relevant issues:
#999, #1069 , #757, #877

### PR DESCRIPTION
**Pull request by vvilpas**
### Summary

DISABLE_CONAN env variable didn't have any effect in build process. This PR solves that.

Fixes #1079

### CODE REVIEW

**Comment by drewrisinger** [comment]
Just to be clear, this removes the ``-DDISABLE_CONAN`` CMake option, correct? Does documentation need to be added to address that?

**Comment by drewrisinger** [comment]
Thanks for the fix, though @vvilpas

**Comment by vvilpas** [comment]
> Just to be clear, this removes the `-DDISABLE_CONAN` CMake option, correct? Does documentation need to be added to address that?

No, it doesn't. It just changes the syntax within CMake, but you can still use `-DDISABLE_CONAN` or the environment variable. Specifying `-DDISABLE_CONAN` takes precedence over the env variable.

**Review by drewrisinger — APPROVED** [review]
* [x] Diff LGTM given comments from @vvilpas 
* [x] Tested build with this patch applied (i.e. just DISABLE_CONAN env var), and it works.

**Review by mtreinish — APPROVED** [review]

**Review by chriseclectic — APPROVED** [review]

**Pull request merged**
