### PR TITLE
Add `__init__.py` to run tests for terra.states

### PR DESCRIPTION
**Pull request by derwind**
### Summary

This PR is to run `test/terra/states/*.py`. Currently `stestr run --slowest` seems not to test them due to lack of `__init__.py`.

### Details and comments

- Add `test/terra/states/__init__.py`.
- You can check this effect by `grep terra.states test_log.txt` after running `stestr run --slowest > test_log.txt 2>&1` in the qiskit-aer root directory.

### CODE REVIEW

**Review by jakelishman — DISMISSED** [review]
Thanks for spotting this!

**Comment by derwind** [comment]
Personally, I intended to focus only on adding `__init__.py `for this assignment. However, in order to merge this PR with unittests passing, we must also update at least `test_aer_statevector.py`, in relation to https://github.com/Qiskit/qiskit-terra/pull/8273 (e.g. `numbers_to_latex_terms(numbers, 15)`). Should I change the title of the issue to address the fix for the tests that do not pass at this time?

**Comment by jakelishman** [comment]
Yeah, we'll need to update the tests in the same PR that activates them, thanks.

**Comment by derwind** [comment]
`test.terra.states.test_aer_statevector.TestAerStatevector.test_drawings` failed due to lack of matplotlib.

Should I modify [this line](https://github.com/Qiskit/qiskit-aer/blob/54dd5700d2b142266d1d120e8ed5dad68cf5811a/.github/workflows/tests.yml#L35) from `pip install -U -c constraints.txt -r requirements-dev.txt qiskit-terra numpy scipy` to `pip install -U -c constraints.txt -r requirements-dev.txt qiskit-terra numpy scipy matplotlib` ?

**Comment by hhorii** [comment]
> Should I modify [this line](https://github.com/Qiskit/qiskit-aer/blob/54dd5700d2b142266d1d120e8ed5dad68cf5811a/.github/workflows/tests.yml#L35) from `pip install -U -c constraints.txt -r requirements-dev.txt qiskit-terra numpy scipy` to `pip install -U -c constraints.txt -r requirements-dev.txt qiskit-terra numpy scipy matplotlib` ?

As [terra does](https://github.com/Qiskit/qiskit-terra/blob/main/requirements-dev.txt#L8), I believe that  `matplotlib` should be in `requirements-dev.txt`.

**Comment by derwind** [comment]
Sorry for the test execution errors persisting. The problem does not occur in my local environment, but it seems to occur on CI, so I tried to examine it with GitHub Actions enabled on my forked repository. The conclusion is that `JUPYTER_PLATFORM_DIRS: 1` is now required, as is [this line](https://github.com/Qiskit/qiskit-terra/blob/main/.azure/test-linux.yml#L180) from Terra.

**Comment by derwind** [comment]
Now we are in a position to pass all tests except Neko Integration. By the way, I am not familiar with Neko Integration, so I'd like to leave it to you...

**Review by hhorii — APPROVED** [review]

**Pull request merged**
